# This workflow tests out new libraries with existing OpenWrt builds to check
# there aren't any compatibility issues. Take a look at Docker/OpenWrt/README.md
name: OpenWrt test

on:
    workflow_call:

jobs:
    build_library:
        name: Compile libwolfssl.so
        runs-on: ubuntu-latest
        # This should be a safe limit for the tests to run.
        timeout-minutes: 4
        container:
            image: alpine:latest
        steps:
            - name: Install required tools
              run: apk add argp-standalone asciidoc bash bc binutils bzip2 cdrkit coreutils diffutils elfutils-dev findutils flex musl-fts-dev g++ gawk gcc gettext git grep intltool libxslt linux-headers make musl-libintl musl-obstack-dev ncurses-dev openssl-dev patch perl python3-dev rsync tar unzip util-linux wget zlib-dev autoconf automake libtool
            - uses: actions/checkout@v3
            - name: Compile libwolfssl.so
              run: ./autogen.sh && ./configure --enable-all && make
            - name: Upload libwolfssl.so
              uses: actions/upload-artifact@v3
              with:
                name: openwrt-libwolfssl.so
                path: src/.libs/libwolfssl.so
                retention-days: 1
    compile_container:
        name: Compile container
        runs-on: ubuntu-latest
        # This should be a safe limit for the tests to run.
        timeout-minutes: 2
        needs: build_library
        strategy:
            fail-fast: false
            matrix:
                release: [ "22.03-SNAPSHOT", "21.02-SNAPSHOT" ] # some other versions: 21.02.0 21.02.5 22.03.0 22.03.3 snapshot
        steps:
            - uses: actions/checkout@v3
            - uses: docker/setup-buildx-action@v2
            - uses: actions/download-artifact@v3
              with:
                name: openwrt-libwolfssl.so
                path: Docker/OpenWrt/.
            - name: Build but dont push
              uses: docker/build-push-action@v3
              with:
                  context: Docker/OpenWrt
                  platforms: linux/amd64
                  push: false
                  tags: openwrt-test:latest
                  build-args: DOCKER_BASE_CONTAINER=openwrt/rootfs:x86-64-${{ matrix.release }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
